site_name: Aeroxee Blog API
theme:
  name: material
  language: id
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select
    - content.code.annotate
nav:
  - Beranda: index.md
  - Memulai: getting_started.md
  - URL Paths:
    - Pendaftarn Akun: paths/register.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences